using UnityEngine;
using UnityEngine.InputSystem;

public class MenuButtonManager : MonoBehaviour
{
    private Camera cam;
    private enum buttonType
    {
        Play,
        Options,
        Credits,
        Quit
    }

    [SerializeField] private buttonType type;

    [SerializeField] Chapter00 chapter00;

    [SerializeField] private GameObject indicationArrow;
    [SerializeField] private GameObject NotebookUI;

    [SerializeField] private NoteBookToggle noteBookToggle;

    [SerializeField] private GameObject optionsMenu;
    [SerializeField] private GameObject creditsMenu;

    [SerializeField] private VolumeControl mainTrack;

    [SerializeField] private AudioSource buttoneClick;

    private bool initialized = false;
    private void Start()
    {
        cam = Camera.main;
    }
    void Update()
    {
        //If there is a touchscreen and the button is currently being pressed
        if (Touchscreen.current != null && Touchscreen.current.primaryTouch.press.wasPressedThisFrame)
        {
            CheckTap(Touchscreen.current.primaryTouch.position.ReadValue());
        }
        //Else if, there is a mouse and left mouse button is being pressed
        else if (Mouse.current != null && Mouse.current.leftButton.wasPressedThisFrame)
        {
            CheckTap(Mouse.current.position.ReadValue());
        }
    }
    void CheckTap(Vector2 screenPos)
    {
        //Gets the screen position generated by Checktap(), converts it into world space, then stores it in a local var named worldPos
        Vector2 worldPos = cam.ScreenToWorldPoint(screenPos);

        //Creates a raycast thing named hit, which is shot from the worldPos and has a direction of Vector2.zero (which means it will only check for collisions at that point)
        RaycastHit2D hit = Physics2D.Raycast(worldPos, Vector2.zero);

        //If the raycast hit something and the thing it hit is the game object
        if (hit.collider != null && hit.collider.gameObject == gameObject)
        {
            //Check if notebook is open || options menu is open || credits menu is open
            if (noteBookToggle.isOpen || optionsMenu.activeSelf || creditsMenu.activeSelf)
            {
                return;
            }   

            switch (type)
            {
                case buttonType.Play:
                    if (!initialized)
                    {
                        chapter00.StartGame();
                        indicationArrow.SetActive(true);
                        NotebookUI.SetActive(true);
                        noteBookToggle.enabled = true;

                        initialized = true;

                        if (mainTrack != null)
                        {
                            mainTrack.FadeToVolume(0.15f, 3f);
                        }

                        buttoneClick.Play();
                    }
                    break;
                case buttonType.Options:
                    optionsMenu.SetActive(true);
                    buttoneClick.Play();
                    break;
                case buttonType.Credits:
                    creditsMenu.SetActive(true);
                    buttoneClick.Play();
                    break;
                case buttonType.Quit:
                    Debug.Log("Quit");
                    buttoneClick.Play();
                    Application.Quit();
                    break;
            }
        }
    }
}
