using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.EnhancedTouch;

public class NoteTakeToggle : MonoBehaviour
{
    [SerializeField] private NoteBookToggle noteBookToggle;
    [SerializeField] private GameObject takeNotesButton;

    private Camera cam;

    [SerializeField] private int holdCounter = 0;
    [SerializeField] private bool noteIsTaken = false;

    void Awake()
    {
        EnhancedTouchSupport.Enable();
    }
    private void Start()
    {
        cam = Camera.main;
        takeNotesButton.SetActive(false);
    }
    void Update()
    {
        if (noteIsTaken) { return;}
        //If there is a touchscreen and the button is currently being pressed
        if (Touchscreen.current != null && Touchscreen.current.primaryTouch.press.isPressed)
        {
            CheckTap(Touchscreen.current.primaryTouch.position.ReadValue());

            if (Touchscreen.current.primaryTouch.press.wasReleasedThisFrame)
            {
                holdCounter = 0;
            }
        }
        //Else if, there is a mouse and left mouse button is being pressed
        else if (Mouse.current != null && Mouse.current.leftButton.isPressed)
        {
            CheckTap(Mouse.current.position.ReadValue());

            if (Mouse.current.leftButton.wasReleasedThisFrame)
            {
                holdCounter = 0;
            }
        }

        else
        {
            holdCounter = 0;
        }
    }
    public void CheckTap(Vector2 screenPos)
    {
        //Gets the screen position generated by Checktap(), converts it into world space, then stores it in a local var named worldPos
        Vector2 worldPos = cam.ScreenToWorldPoint(screenPos);

        //Creates a raycast thing named hit, which is shot from the worldPos and has a direction of Vector2.zero (which means it will only check for collisions at that point)
        RaycastHit2D hit = Physics2D.Raycast(worldPos, Vector2.zero);

        //If the raycast hit something and the thing it hit is the game object
        if (hit.collider != null && hit.collider.gameObject == gameObject)
        {
            holdCounter += 1;

            if (holdCounter >= 60)
            {
                holdCounter = 0;
                takeNotesButton.SetActive(true);
            }
        }
    }
    public void NoteTaken()
    {
        noteIsTaken = true;
    }
    public void NoteUnTaken()
    {
        noteIsTaken = false;
    }

}
